### ISSUE TITLE
Load testing for up to 2,000 concurrent users

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1884]
### Summary

This task is to run a load test with [our artillery setup](https://github.com/HHS/simpler-grants-gov/blob/main/api/artillery-load-test.yml) on the production search api. 

Steps:

* Schedule time to run the load test
* Run artillery locally as an individual or group
* Share results

### Acceptance criteria

- [ ] Run load test and share results
- [ ] Create needed follow up ticket

**Comment by coilysiren** [comment]
I'm going to load test at 3 different levels, of decreasing load:

level 3

```yaml
  phases:
    - duration: 300
      arrivalRate: 10
      maxVusers: 100
      name: Warm up phase
    - duration: 300
      arrivalRate: 500
      maxVusers: 5000
      name: Ramp up load
    - duration: 300
      arrivalRate: 1000
      maxVusers: 10000
      name: Spike phase
```

level 2

```yaml
  phases:
    - duration: 300
      arrivalRate: 10
      maxVusers: 100
      name: Warm up phase
    - duration: 300
      arrivalRate: 250
      maxVusers: 2500
      name: Ramp up load
    - duration: 300
      arrivalRate: 500
      maxVusers: 5000
      name: Spike phase
```

level 1:

```yaml
  phases:
    - duration: 300
      arrivalRate: 10
      maxVusers: 50
      name: Warm up phase
    - duration: 300
      arrivalRate: 100
      maxVusers: 1000
      name: Ramp up load
    - duration: 300
      arrivalRate: 200
      maxVusers: 2000
      name: Spike phase
```

Will post results when I have them, these load tests take a long time to run...
