### ISSUE TITLE
Setup pre-commit hooks for the API folder to check that code passes our linting checks

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#2363]
### Summary

First figure out what tech we use (pre-commit or something else).

This should run the following commands locally (making a single make command that does all of these might be better - `make check` does most of this):
* `make format-check`
* `make lint`
* `make db-check-migrations`
* `make lint-security`
* `make test`

Whatever approach we take should be skippable to avoid blocking someone making a branch that they can share without being 100% valid.

### Acceptance criteria

- [ ] Implement a pre-commit hook that will run our format/lint checks when someone attempts to create a commit in the api folder

**Comment by chouinar** [comment]
Looking into this a bit, we actually hav a pre-commit config at the root of the repo already, although very little configured within it.

A very rough approach we might take for running our make commands is adding something like:
```yaml
- repo: local
  hooks:
    - id: api-custom
      name: API linting
      description: TODO - the api linting
      entry: make -C api lint
      language: system
      types: [python]
      pass_filenames: false
      files: api/
```

Naming aside, this makes it so when you attempt to do `git commit`, it runs the given make command. In this case, if I have something invalid in the file format, the linter will complain when I try to commit. You can work around the checks entirely by doing `git commit --no-verify`

**Comment by acouch** [comment]
Pre-commit doesn't support monorepos intentionally https://github.com/pre-commit/pre-commit/issues/466 , though locally I did find that I could get it to work with npm with something like:

```yml
    - id: frontend-format
      name: Frontend Format Check
      entry: bash ./bin/pre-commit-frontend.sh format-check
      language: system
      pass_filenames: false
      files: frontend/
```

With `./bin/pre-commit-frontend.sh`:

```bash
#/bin/bash

cd "frontend" && npm run $1
``` 

That would run format-check against all of the files. If we wanted to just those from the commit we could grab them in a the bash file and loop through each one `git diff --name-only --cached`, but would need to do the format/lint/ts:check calls directly or update the `package.json` file to take a file arg if provided.
